-- Migration: AI-Powered Outbound Operating System Tables

-- 1. Research Artifacts Table
CREATE TABLE IF NOT EXISTS deorch_research (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  company_summary TEXT,
  industry TEXT,
  business_model TEXT,
  target_audience TEXT,
  products_services JSONB DEFAULT '[]'::jsonb,
  positioning TEXT,
  company_signals JSONB DEFAULT '[]'::jsonb,
  recent_relevant_information JSONB DEFAULT '[]'::jsonb,
  relevant_people_context TEXT,
  research_points JSONB DEFAULT '[]'::jsonb,
  sources JSONB DEFAULT '[]'::jsonb,
  confidence TEXT DEFAULT 'medium',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Website Audits Table
CREATE TABLE IF NOT EXISTS deorch_website_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  overall_score INT DEFAULT 0,
  category_scores JSONB DEFAULT '{}'::jsonb,
  strengths JSONB DEFAULT '[]'::jsonb,
  issues JSONB DEFAULT '[]'::jsonb,
  opportunities JSONB DEFAULT '[]'::jsonb,
  priority TEXT DEFAULT 'medium',
  recommendations JSONB DEFAULT '[]'::jsonb,
  evidence JSONB DEFAULT '[]'::jsonb,
  pages_scraped JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Outreach Strategies Table
CREATE TABLE IF NOT EXISTS deorch_outreach_strategies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  primary_opportunity TEXT,
  secondary_opportunity TEXT,
  recommended_angle TEXT,
  why_this_matters TEXT,
  supporting_evidence JSONB DEFAULT '[]'::jsonb,
  suggested_cta TEXT,
  things_to_avoid JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Generated Messages & Sequences Table
CREATE TABLE IF NOT EXISTS deorch_generated_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  stage TEXT DEFAULT 'initial',
  subject TEXT,
  body TEXT,
  angle_used TEXT,
  status TEXT DEFAULT 'draft',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Reply Analysis Table
CREATE TABLE IF NOT EXISTS deorch_reply_analysis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  reply_text TEXT NOT NULL,
  category TEXT NOT NULL,
  sentiment_context TEXT,
  recommended_next_action TEXT,
  suggested_response TEXT,
  confidence FLOAT DEFAULT 0.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. AI Activity & Observability Table
CREATE TABLE IF NOT EXISTS deorch_ai_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  task TEXT NOT NULL,
  status TEXT NOT NULL,
  prompt_tokens INT DEFAULT 0,
  completion_tokens INT DEFAULT 0,
  latency_ms INT DEFAULT 0,
  error_message TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_deorch_research_lead ON deorch_research(lead_id);
CREATE INDEX IF NOT EXISTS idx_deorch_audits_lead ON deorch_website_audits(lead_id);
CREATE INDEX IF NOT EXISTS idx_deorch_strategies_lead ON deorch_outreach_strategies(lead_id);
CREATE INDEX IF NOT EXISTS idx_deorch_messages_lead ON deorch_generated_messages(lead_id);
CREATE INDEX IF NOT EXISTS idx_deorch_activity_lead ON deorch_ai_activity(lead_id);
