-- Migration: Evidence-Based Research & Commercial Opportunities System

-- 1. Evidence Storage Table
CREATE TABLE IF NOT EXISTS deorch_research_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  evidence_key TEXT NOT NULL,
  type TEXT NOT NULL, -- 'fact' | 'observation' | 'inference'
  claim TEXT NOT NULL,
  content TEXT,
  source_url TEXT,
  source_title TEXT,
  source_type TEXT NOT NULL, -- 'company_website' | 'external_web' | 'news' | 'social' | 'existing_deorch_data'
  confidence TEXT NOT NULL, -- 'verified' | 'observed' | 'ai_inference'
  supporting_evidence_keys JSONB DEFAULT '[]'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Commercial Opportunities Table
CREATE TABLE IF NOT EXISTS deorch_commercial_opportunities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  opportunity TEXT NOT NULL,
  why_it_matters TEXT NOT NULL,
  supporting_evidence_keys JSONB DEFAULT '[]'::jsonb,
  priority TEXT DEFAULT 'high',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_deorch_evidence_lead ON deorch_research_evidence(lead_id);
CREATE INDEX IF NOT EXISTS idx_deorch_evidence_key ON deorch_research_evidence(evidence_key);
CREATE INDEX IF NOT EXISTS idx_deorch_opportunities_lead ON deorch_commercial_opportunities(lead_id);
