-- Migration: Ensure all structured AI research fields are present in deorch_research
-- Stores the 6 core components of the Evidence Research Agent:
-- 1. Company Research (company_summary, industry, business_model, target_audience, key_offerings, positioning)
-- 2. Facts (facts JSONB)
-- 3. Observations (observations JSONB)
-- 4. Inferences (inferences JSONB)
-- 5. Research Points (research_points JSONB)
-- 6. Commercial Opportunities (commercial_opportunities JSONB)
-- Linked by lead_id = deorch_leads.id

CREATE TABLE IF NOT EXISTS deorch_research (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  company_summary TEXT,
  industry TEXT,
  business_model TEXT,
  target_audience TEXT,
  key_offerings JSONB DEFAULT '[]'::jsonb,
  positioning TEXT,
  facts JSONB DEFAULT '[]'::jsonb,
  observations JSONB DEFAULT '[]'::jsonb,
  inferences JSONB DEFAULT '[]'::jsonb,
  commercial_opportunities JSONB DEFAULT '[]'::jsonb,
  research_points JSONB DEFAULT '[]'::jsonb,
  company_signals JSONB DEFAULT '[]'::jsonb,
  recent_relevant_information JSONB DEFAULT '[]'::jsonb,
  relevant_people_context TEXT,
  sources JSONB DEFAULT '[]'::jsonb,
  evidence_summary JSONB DEFAULT '{}'::jsonb,
  confidence TEXT DEFAULT 'medium',
  provider TEXT,
  model TEXT,
  latency_ms INT,
  researched_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  products_services JSONB DEFAULT '[]'::jsonb
);

-- Ensure all columns are added safely if table was already created
ALTER TABLE deorch_research 
  ADD COLUMN IF NOT EXISTS company_summary TEXT,
  ADD COLUMN IF NOT EXISTS industry TEXT,
  ADD COLUMN IF NOT EXISTS business_model TEXT,
  ADD COLUMN IF NOT EXISTS target_audience TEXT,
  ADD COLUMN IF NOT EXISTS key_offerings JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS positioning TEXT,
  ADD COLUMN IF NOT EXISTS facts JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS observations JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS inferences JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS commercial_opportunities JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS research_points JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS company_signals JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS recent_relevant_information JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS relevant_people_context TEXT,
  ADD COLUMN IF NOT EXISTS sources JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS evidence_summary JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS confidence TEXT DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS provider TEXT,
  ADD COLUMN IF NOT EXISTS model TEXT,
  ADD COLUMN IF NOT EXISTS latency_ms INT,
  ADD COLUMN IF NOT EXISTS researched_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  ADD COLUMN IF NOT EXISTS products_services JSONB DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_deorch_research_lead ON deorch_research(lead_id);
