-- Migration: Add structured AI research fields to deorch_research table
-- Ensures direct storage of all 6 Research Agent output components:
-- 1. company_research (JSONB)
-- 2. facts (JSONB)
-- 3. observations (JSONB)
-- 4. inferences (JSONB)
-- 5. research_points (JSONB)
-- 6. commercial_opportunities (JSONB)
-- linked by lead_id = deorch_leads.id

-- Step 1: Create deorch_research table if it doesn't exist yet
CREATE TABLE IF NOT EXISTS deorch_research (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES deorch_leads(id) ON DELETE CASCADE,
  company_research JSONB DEFAULT '{}'::jsonb,
  facts JSONB DEFAULT '[]'::jsonb,
  observations JSONB DEFAULT '[]'::jsonb,
  inferences JSONB DEFAULT '[]'::jsonb,
  research_points JSONB DEFAULT '[]'::jsonb,
  commercial_opportunities JSONB DEFAULT '[]'::jsonb,
  company_summary TEXT,
  industry TEXT,
  business_model TEXT,
  target_audience TEXT,
  products_services JSONB DEFAULT '[]'::jsonb,
  positioning TEXT,
  company_signals JSONB DEFAULT '[]'::jsonb,
  recent_relevant_information JSONB DEFAULT '[]'::jsonb,
  relevant_people_context TEXT,
  sources JSONB DEFAULT '[]'::jsonb,
  confidence TEXT DEFAULT 'medium',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 2: In case deorch_research already exists, safely add the new columns
ALTER TABLE deorch_research 
  ADD COLUMN IF NOT EXISTS company_research JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS facts JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS observations JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS inferences JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS research_points JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS commercial_opportunities JSONB DEFAULT '[]'::jsonb;

-- Step 3: Performance index on lead_id
CREATE INDEX IF NOT EXISTS idx_deorch_research_lead ON deorch_research(lead_id);
